DefaultContentLanguage = "cn"
baseURL = "https://blog.joway.io/"
canonifyURLs = false
enableRobotsTXT = true
enableGitInfo = true
hasCJKLanguage = true
summaryLength = 120
locale = "zh-CN"
theme = "yinyang"
title = "Random Thoughts"

# [related]
# includeNewer = true
# threshold = 80
# toLower = false
# [[related.indices]]
# name = "date"
# weight = 100
# [[related.indices]]
# name = "keywords"
# weight = 100

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[frontmatter]
lastmod = ["lastmod", ":git", "date", "publishDate"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
guessSyntax = true
noClasses = false
style = "tango"
tabWidth = 2

[languages]
# [languages.en]
#   contentDir = "content/en"
#   languageName = "English"
#   weight = 1
[languages.cn]
contentDir = "content/cn"
label = "简体中文"
weight = 2

[params]
TwitterCards = true
description = "100% human native." 
disqus = "joway" # disqus account name
extraHead = '<script defer src="https://www.googletagmanager.com/gtag/js?id=G-X7BH3GLYYE"></script><script defer src="https://cdn.jsdelivr.net/gh/joway/homepage/analytics.js"></script><script defer src="https://mailbike.dev/widget.js" data-app="mb_live_6b2f3a85cd570022"></script><script defer src="https://argos.elsetech.app/script.js" data-website-id="92ece2e1-4448-4499-a252-d4a933385f36"></script><script defer src="https://widget.elsetech.app/aidaily.js"></script>' 
favicon = "/logo.png" 
headTitle = "Random Thoughts" 
mainSections = ["posts"] 
postFooterContent = '<br/><br/><p>Subscribe：<a target="_blank" href="https://mailchi.mp/a1a0d59e7a19/joway"><b>Mailchimp</b></a></p><br/><a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://blog.joway.io/images/cc.png" /></a>' 
postHeaderContent = "" 
# extraBody = ''
# postAds = '<ins class="adsbygoogle" style="display:block" data-ad-client="ca-pub-6400651395935595" data-ad-slot="5705651853" data-ad-format="auto" data-full-width-responsive="true"></ins>'

[params.author]
homepage = "https://joway.io/"
name = "Joway"

# [[params.socials]]
# name = "Telegram"
# link = "https://t.me/biosthinking"

# [[params.socials]]
# name = "Slides"
# link = "/presentations"

[[params.socials]]
link = "https://mailchi.mp/a1a0d59e7a19/joway"
name = "Subscribe"
[[params.socials]]
name = "RSS"
link = "/index.xml"
[[params.socials]]
link = "/travel"
name = "Travel"
[[params.socials]]
link = "https://joway.io"
name = "About"
